#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "spin-app"
version = "0.1.0"
authors = ["ozcan"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin-app"

[component.spin-app]
source = "target/wasm32-wasip2/release/spin_app.wasm"
allowed_outbound_hosts = []
[component.spin-app.build]
command = "cargo build --target wasm32-wasip2 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
